"""INDEX.md regenerator for the video store.

data/videos/*/summary.md -> parse frontmatter -> data/videos/INDEX.md

In: store root (default data/videos).
Out: JSON {ok, count, path} on stdout.
State: rewrites <root>/INDEX.md.

Index exists so triage reads one small file instead of every summary.
"""

import argparse
import json
import sys
from pathlib import Path

NAME = "youtube_index"
DESCRIPTION = "Regenerate data/videos/INDEX.md from per-video summary frontmatter."
INPUT_SCHEMA = {
    "root": {
        "type": "string",
        "required": False,
        "description": "Video store root; defaults to data/videos.",
    },
}

_FIELDS = ("video_id", "title", "channel", "duration", "added", "status", "url")


def parse_frontmatter(text: str) -> dict:
    """Extract a flat YAML-ish frontmatter block.

    In: file text starting with '---'.
    Out: dict of key -> string value; empty when no block.
    """
    if not text.startswith("---"):
        return {}
    lines = text.splitlines()
    out = {}
    for line in lines[1:]:
        if line.strip() == "---":
            break
        if ":" not in line:
            continue
        key, _, value = line.partition(":")
        out[key.strip()] = value.strip()
    return out


def invoke(root: str = "data/videos", **_kwargs) -> dict:
    """Rebuild the store index from summary frontmatter.

    In: store root.
    Out: dict with ok flag, count indexed, index path.
    State: writes <root>/INDEX.md.
    """
    root_path = Path(root)
    if not root_path.is_dir():
        return {"ok": False, "error": f"store root not found: {root}"}

    rows = []
    for summary in sorted(root_path.glob("*/summary.md")):
        meta = parse_frontmatter(summary.read_text(encoding="utf-8"))
        if not meta.get("video_id"):
            continue
        rows.append({field: meta.get(field, "") for field in _FIELDS})

    rows.sort(key=lambda r: r.get("added", ""), reverse=True)

    lines = [
        "# Video index",
        "",
        f"{len(rows)} video(s). Regenerated by `agents/youtube/index.py` — do not edit by hand.",
        "",
        "| Added | Status | Title | Channel | Duration | ID |",
        "|---|---|---|---|---|---|",
    ]
    for r in rows:
        title = r["title"].replace("|", "\\|")
        channel = r["channel"].replace("|", "\\|")
        lines.append(
            f"| {r['added']} | {r['status']} | {title} | {channel} "
            f"| {r['duration']} | {r['video_id']} |"
        )
    lines.append("")

    index_path = root_path / "INDEX.md"
    index_path.write_text("\n".join(lines), encoding="utf-8")

    return {"ok": True, "count": len(rows), "path": str(index_path)}


def main() -> int:
    parser = argparse.ArgumentParser(description=DESCRIPTION)
    parser.add_argument("--root", default="data/videos", help="Video store root")
    args = parser.parse_args()

    result = invoke(root=args.root)
    print(json.dumps(result, indent=2, ensure_ascii=False))
    return 0 if result.get("ok") else 1


if __name__ == "__main__":
    sys.exit(main())
